Repository danielsaad/ds-contest-tools, pull requests merged in 2023-02, with the labels that each got.

#28 Changed compiler for C
  arquivos/Makefile
Labels: enhancement

#27 Added coments and code reviewed
  .clang-format
  .gitignore
  boca.py
  build.py
  contest.py
  convert.py
  fileutils.py
  jsonutils.py
  latexutils.py
  logger.py
  metadata.py
  pdfutils.py
  polygon_converter.py
  polygon_submitter.py
  statement_converter.py
  toolchain.py
  utils.py
Labels: enhancement

#26 Dev silent checker
  build.py
  checker.py
  toolchain.py
Labels: bug, enhancement

#29 Dev silent checker
  checker.py
  utils.py
Labels: enhancement, good first issue
